export const POST_FETCH = "POST/FETCH"
export const POST_FETCH_SUCCESS = "POST/FETCH/SUCCESS"
export const POST_FETCH_FAIL = "POST/FETCH/FAIL"

export const MainPost_FETCH = "POST/FETCH/MainPost"
export const MainPOST_FETCH_SUCCESS = "POST/FETCH/MainPost/SUCCESS"
export const MainPOST_FETCH_FAIL = "POST/FETCH/MainPost/FAIL"

export const POST_ADD = "POST/ADD"
export const POST_ADD_SUCCESS = "POST/ADD/SUCCESS"
export const POST_ADD_FAIL= "POST/ADD/FAIL"
export const POST_ADD_STATUS_RESET = "POST/ADD/STATUS/RESET"

export const POST_INIT_PAGE_INFO = "POST/INIT/PAGE/INFO"

export const POST_DELETE = "POST/DELETE"
export const POST_DELETE_SUCCESS = "POST/DELETE/SUCCESS"
export const POST_DELETE_FAIL = "POST/DELETE/FAIL"