export const TOPIC_FETCH = "TOPIC/FETCH"
export const TOPIC_FETCH_SUCCESS = "TOPIC/FETCH/SUCCESS"
export const TOPIC_FETCH_FAIL = "TOPIC/FETCH/FAIL"

export const TOPIC_ADD = "TOPIC/ADD"
export const TOPIC_ADD_SUCCESS = "TOPIC/ADD/SUCCESS"
export const TOPIC_ADD_FAIL = "TOPIC/ADD/FAIL"
export const TOPIC_ADD_STATUS_RESET= "TOPIC/ADD/STATUS/RESET"


export const TOPIC_DELETE = "TOPIC/DELETE"
export const TOPIC_DELETE_SUCCESS = "TOPIC/DELETE/SUCCESS"
export const TOPIC_DELETE_FAIL= "TOPIC/DELETE/SUCCESS"